apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      imagePullSecrets:
       - name: secret
      containers:
        - name: angular
          image: solange883/eventmanager:front  
          ports:
            - containerPort: 80  
                    
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80                         
      targetPort: 80                    
  type: LoadBalancer                  
