apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-backend
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: solange883/backend:latest 
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: eventmanager
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
      volumes:
        - name: storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
